"""Shared rule/variant data for normalization."""

from __future__ import annotations

# 도메인 패턴 결합 규칙
JOIN_RULES = [
    (r"\bload\s*[-\s]*lock\b", "loadlock"),
    (r"\bball\s*[-\s]*screw\b", "ball_screw"),
    (r"\b(ll|ch)\s*([0-9]+)\b", r"\1\2"),  # ll 1 -> ll1
    (r"\bpm\s*([0-9])\s*-\s*([0-9])\b", r"pm\1_\2"),  # pm 2-1 -> pm2_1
    (r"\b(ipc|dpcb|dpcp)\s*([0-9]{3,4})\b", r"\1\2"),
    (r"(?<=\d)\s*hr\b", "hr"),
    (r"(?<=\d)\s*um\b", "um"),
]

# L5 변형어 맵 (반도체 도메인)
L5_VARIANT_MAP = {
    # 설비/모듈 약어
    "efem": "EFEM",
    "fm": "EFEM",
    "tm": "TM",
    "am": "AM",
    "pm": "PM",
    "ll": "LL",
    "ll1": "LL1",
    "ll2": "LL2",
    "ch": "CH",
    "ch1": "CH1",
    "ch2": "CH2",
    "ctr": "CTR",
    "ctc": "CTC",
    "aps": "APS",
    "awp": "AWP",
    "awp cal": "AWP CAL",
    "aab": "AAB",
    "bba": "BBA",
    "aba": "ABA",
    "bab": "BAB",
    "oht": "OHT",
    "mfc": "MFC",
    "ffu": "FFU",
    "d-net": "D-NET",
    "d net": "D-NET",
    "dnet": "D-NET",
    "d-net board": "D-NET BOARD",
    "dnet board": "D-NET BOARD",
    "pdb": "PDB",
    "ems": "EMS",
    "sry": "SRY",
    "sry1": "SRY1",
    "sry2": "SRY2",
    "jig": "JIG",
    "lp": "LP",
    "lp1": "LP1",
    "lp2": "LP2",
    "lp3": "LP3",
    "ed cal": "ED CAL",
    "ed-cal": "ED CAL",
    "2pt cal": "2POINT CAL",
    "2 point cal": "2POINT CAL",
    "2point cal": "2POINT CAL",
    "two point cal": "2POINT CAL",
    "gap cal": "GAP CAL",
    "gap sensor cal": "GAP SENSOR CAL",
    "gap teaching": "GAP TEACHING",
    "teaching": "TEACHING",
    "centerning": "CENTERING",
    "centering": "CENTERING",
    "cwac": "CWAC",
    "macro": "MACRO",
    "spec in": "SPEC IN",
    "spec out": "SPEC OUT",
    "backup": "BACKUP",
    "back up": "BACKUP",
    "bu": "BACKUP",
    # 밸브/게이지/압력 관련
    "apc": "APC",
    "pendulum valve": "APC",
    "slot vv": "SLOT VALVE",
    "slot v/v": "SLOT VALVE",
    "slot v/v head": "SLOT VALVE HEAD",
    "slot valve head": "SLOT VALVE HEAD",
    "head o-ring": "HEAD O-RING",
    "o-ring": "O-RING",
    "baratron": "BARATRON",
    "b.g": "BARATRON",
    "bg": "BARATRON",
    "baratron gauge": "BARATRON GAUGE",
    "bara": "BARATRON",
    "pirani": "PIRANI",
    "pirani gauge": "PIRANI GAUGE",
    "convectron": "CONVECTRON",
    "convectron gauge": "CONVECTRON GAUGE",
    "manometer": "MANOMETER",
    "he leak check": "HELIUM LEAK CHECK",
    "helium check": "HELIUM LEAK CHECK",
    "he leak": "HELIUM LEAK CHECK",
    "leak check": "HELIUM LEAK CHECK",
    "pressure": "PRESSURE",
    "gas box exhasut": "GAS BOX EXHAUST",
    "exhasut": "EXHAUST",
    # 프로세스 킷/부품
    "process kit": "PROCESS KIT",
    "gdp": "GDP",
    "u-elt": "UPPER ELT",
    "upper elt": "UPPER ELT",
    "lower elt": "LOWER ELT",
    "iso ring": "ISO RING",
    "iso-ring": "ISO RING",
    "iso ring 02": "ISO RING 02",
    "exhaust ring": "EXHAUST RING",
    "baffle": "BAFFLE",
    "pnc baffle": "PNC BAFFLE",
    "ncb": "NCB",
    "aicp": "AICP",
    "aicp source": "AICP SOURCE",
    "matcher": "MATCHER",
    "generator": "GENERATOR",
    "present sensor": "PRESENT SENSOR",
    "tp3": "TP3",
    "pin bellows": "PIN BELLOWS",
    "bellows": "BELLOWS",
    "pin holder": "PIN HOLDER",
    "peek plate": "PEEK PLATE",
    "chuck": "CHUCK",
    "dot chuck": "DOT CHUCK",
    "chuck heater dot1": "CHUCK HEATER DOT1",
    "carved shaft": "CARVED SHAFT",
    "ball screw": "BALL SCREW",
    "timing pulley": "TIMING PULLEY",
    "motor pulley": "MOTOR PULLEY",
    "timing belt": "TIMING BELT",
    "bush": "BUSH",
    "shaft": "SHAFT",
    "diffuser": "DIFFUSER",
    "view port": "VIEW PORT",
    "viewport": "VIEW PORT",
    "solenoid valve": "SOLENOID VALVE",
    "sol block": "SOL BLOCK",
    "molex": "MOLEX",
    # 시험/테스트/운전 상태
    "partition test": "PARTITION TEST",
    "normal test": "NORMAL TEST",
    "transfer test": "TRANSFER TEST",
    "leak": "LEAK",
    "pumping": "PUMPING",
    "purge": "PURGE",
    "n2 blowing": "N2 BLOWING",
    "di clean": "DI CLEAN",
    "ipa cln": "IPA CLEAN",
    "di cln": "DI CLEAN",
    "vacuum clean": "VACUUM CLEAN",
    "manual leak check": "HELIUM LEAK CHECK",
    "auto leak check": "HELIUM LEAK CHECK",
    "open/close time": "OPEN/CLOSE TIME",
    "open close time": "OPEN/CLOSE TIME",
    "cycle": "CYCLE",
    "ignition": "IGNITION",
    "standby": "STANDBY",
    "run": "RUN",
    "dummy": "DUMMY",
    "dummy wafer": "DUMMY",
    "4매": "4EA",
    "5매": "5EA",
    "10매": "10EA",
    # 신호/알람/데이터
    "alarm": "ALARM",
    "interlock": "INTERLOCK",
    "job abort": "JOB ABORT",
    "fdc": "FDC",
    "fdc data": "FDC DATA",
    "trend": "TREND",
    "reading": "READING",
    "offset": "OFFSET",
    "margin": "MARGIN",
    "hunting": "HUNTING",
    "logic alarm": "LOGIC ALARM",
    "timeout": "TIMEOUT",
    # 추가 커버리지
    "open close": "OPEN/CLOSE",
    "open/close": "OPEN/CLOSE",
    "o/c": "OPEN/CLOSE",
    "spec-in": "SPEC IN",
    "specin": "SPEC IN",
    "specout": "SPEC OUT",
    "wafer sliding": "SLIDING",
    "sliding": "SLIDING",
    "y축": "Y-AXIS",
    "z축": "Z-AXIS",
    # PC(Particle) 통일
    "p.c": "PC",
    "pc": "PC",
    "particle": "PC",
    "pc spec out": "PC SPEC OUT",
    "pc 발생": "PC 발생",
    "pc map": "PC MAP",
}

__all__ = ["JOIN_RULES", "L5_VARIANT_MAP"]
